# -*- coding: utf-8 -*-
"""hangman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6uAYjUkmAyvrVnsKC8FlNvZT5pX5OE7
"""

import random

# List of words
word_list = ['python', 'hangman', 'developer', 'codealpha', 'project', 'simple', 'banana']

# Choose a random word
chosen_word = random.choice(word_list)
word_length = len(chosen_word)

# Display: underscores for letters
display = ['_'] * word_length

# Number of chances
lives = 6

# Store already guessed letters
guessed_letters = []

print("🎮 Welcome to Hangman Game!")
print("Guess the word, one letter at a time.")
print("You have", lives, "lives. Let's start!\n")

# Game loop
while lives > 0 and '_' in display:
    print("Word: ", ' '.join(display))
    guess = input("Guess a letter: ").lower()

    if guess in guessed_letters:
        print("You already guessed that letter.\n")
        continue

    guessed_letters.append(guess)

    if guess in chosen_word:
        for i in range(word_length):
            if chosen_word[i] == guess:
                display[i] = guess
        print("✅ Good guess!\n")
    else:
        lives -= 1
        print("❌ Wrong guess. You have", lives, "lives left.\n")

# Result
if '_' not in display:
    print("🎉 Congratulations! You guessed the word:", chosen_word)
else:
    print("💀 Game Over! The word was:", chosen_word)